### ISSUE TITLE
Feature Request: Update Toggle Fader Mute to include distinct Toggle/Mute/Unmute options

### ISSUE THREAD

**Issue by breon** [FrostyCoolSlug/goxlr-utility-streamdeck#2]
Hi there! Thanks for building this plugin. It's been great so far.

I started to integrate some of the features into my multi-actions on my Stream Deck, but then realized that since it's a toggle, I can't predictably set my fader states to exactly what I want. If there were options for Toggle (existing), Mute and Unmute, you could set a direct fader state.

As a GoXLR Utility and Stream Deck user, I would like to select Toggle, Mute and Unmute for the Toggle Fader Mute feature, so that I can directly set a desired state

### Preconditions

- User has GoXLR Utility installed and running
- User has stream deck plugin installed
- Stream deck plugin is connected to GoXLR

### Steps

- User drags Fader Mute feature to stream deck button
   - Config panel appears
      - Text Field: "Title"
      - Dropdown: "Fader"
         - Options: Fader 1-4
      - Dropdown: "State"
         - Option: "Toggle"
         - Option: "Mute"
         - Option: "Unmute"
      - Dropdown: "Behaviour"
         - Option: "Mute to X"
         - Option: "Mute to All"
      - Button: "Refresh"
- User enters desired title
- User selects desired fader
- User selects desired state
- User select desired bahaviour
- User pushes button

### Expected
- Fader mutes, unmutes or toggles states based on user's behaviour selection

**Comment by breon** [comment]
If you didn't want to modify the existing action, this could totally be a separate action like "Fader Mute/Unmute", but for the sake of keeping the action list a little cleaner, adding the new options to the existing action would be nice.

**Comment by FrostyCoolSlug** [comment]
Sorry for the delayed reply, I've not really had much time to look at this plugin, I'm planing a feature pass on it soon just to bring more options, I'll look into adding this as well.

**Comment by breon** [comment]
No worries. The plugin has been working great! Thanks for working on it.

**Comment by FrostyCoolSlug** [comment]
This has been added with the 0.3.0 release. Not quite as described above, but the result is the same :)
